<?php

include dirname(__FILE__) .'/views_jqgrid.theme.inc';

/**
 * Implementation of hook_views_api().
 */
// JEFF - This tells views that this module provides Views support and uses Views API v.2
function views_jqgrid_views_api() {
  return array(
    'api' => 2,
  );
}

/*
 * Implementation of hook_theme()
 */
function views_jqgrid_theme() {
  return array(
    // On behalf of a plugin
    'views_jqgrid_style_plugin_jqgrid' => array(
      'arguments' => array('form' => NULL),
    ),
  );
}


function theme_views_jqgrid_style_plugin_jqgrid($form) {
// This form is reached via views:  style, then settings
  $output = drupal_render($form['description_markup']);

  $header = array(
    t('Field'),
    t('Column'),
    t('Separator'),
    t('Width (px)'),
    array(
      'data' => t('Sortable'),
      'align' => 'center',
    ),
    array(
      'data' => t('Default sort'),
      'align' => 'center',
    ),
  );
  $rows = array();
  foreach (element_children($form['columns']) as $id) {
    $row = array();
    $row[] = drupal_render($form['info'][$id]['name']);
    $row[] = drupal_render($form['columns'][$id]);
    $row[] = drupal_render($form['info'][$id]['separator']);
    $row[] = drupal_render($form['info'][$id]['width']);
    if (!empty($form['info'][$id]['sortable'])) {
      $row[] = array(
        'data' => drupal_render($form['info'][$id]['sortable']),
        'align' => 'center',
      );
      $row[] = array(
        'data' => drupal_render($form['default'][$id]),
        'align' => 'center',
      );
    }
    else {
      $row[] = '';
      $row[] = '';
    }
    $rows[] = $row;
  }

  // Add the special 'None' row.
  $rows[] = array(t('None'), '', '', '', '', array('align' => 'center', 'data' => drupal_render($form['default'][-1])));

  $output .= theme('table', $header, $rows);
  $output .= drupal_render($form);
  return $output;
}

function views_jqgrid_menu() {
  $items['views_jqgrid'] = array(
    'title' => 'Views',
    'page callback' => 'views_jqgrid_get_items',
    'access callback' => 'user_access',
    'access arguments' => array('access content'),
    'description' => 'Ajax callback for view loading.',
    'file' => 'views_jqgrid_ajax.inc',
    'type' => MENU_CALLBACK,
  );
  return $items;
}